config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
  sessions: 'admins/sessions',
  passwords: 'admins/passwords',
  registrations: 'admins/registrations'
}
  devise_for :customers, controllers: {
  sessions: 'customers/sessions',
  passwords: 'customers/passwords',
  registrations: 'customers/registrations'
}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope module: :admins do
    get '/admin', to: 'homes#top'
  end

  namespace :admins do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]

  end

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update] do
      get :check
      patch :destroy
    end
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete :destroy_all
      end
    end
    resources :orders, only: [:index, :new, :create, :show]do
      collection do
        get :check
        get :thanks
      end
    end

  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def active_for_authentication?
    super && (self.is_active == true)
  end

end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
    @customers = Customer.page(params[:page]).per(10)
  end

  def create
  end

  def show
    @customer =  Customer.find(params[:id])
  end

  def edit
    @customer =  Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admins_customer_path(@customer)
  end

  private

  def customer_params
    params.require(:customer).permit(:email, :password, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
     customer_path(resource)
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admins/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 my-5">
      <h1><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h1>
      <%= form_with model: @customer,url: admins_customer_path, method: :patch, local:true do |f| %>
        <tr>
          <div class="d-flex flex-row bd-highlight mb-3">
            <div class="col-sm-3">
             <th>会員ID</th>
            </div>
            <div class ="offset-sm-1">
             <td><%= @customer.id %></td>
            </div>
          </div>
        </tr>
        <div class="field">
          <div>
            <%= f.label "氏名", class: "col-sm-3 control-label" %>
            <%= f.text_field :last_name %>
            <%= f.text_field :first_name %>
          </div>
        </div>

        <div class="field">
          <div>
            <%= f.label "フリガナ", class: "col-sm-3 control-label" %>
            <%= f.text_field :last_name_kana %>
            <%= f.text_field :first_name_kana %>
          </div>
        </div>

        <div class="field">
          <div>
            <%= f.label "郵便番号", class: "col-sm-3 control-label" %>
            <%= f.text_field :postal_code %>
          </div>
        </div>

        <div class="field">
          <div>
            <%= f.label "住所", class: "col-sm-3 control-label" %>
            <%= f.text_field :address %>
          </div>
        </div>

        <div class="field">
          <div>
            <%= f.label "電話番号", class: "col-sm-3 control-label" %>
            <%= f.text_field :telephone_number %>
          </div>
        </div>

        <div class="field">
          <div>
            <%= f.label "メールアドレス", class: "col-sm-3 control-label" %>
            <%= f.email_field :email, autocomplete: "email" %>
          </div>
        </div>

        <div class="field">
          <div>
            <%= f.label "会員ステータス", class: "col-sm-3 control-label" %>
            <%= f.select :is_active ,[['有効',true],['退会',false]] %><%# チェックボックス %>
          </div>
        </div>

        <div class="offset-md-3 mt-3">
            <%= f.submit "変更を保存", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 my-5">
        <h1>会員一覧</h1>
        <table class="table genre-index table-bordered">
          <thead>
            <tr>
              <td>会員ID</td>
              <td>氏名</td>
              <td>メールアドレス</td>
              <td>ステータス</td>
            </tr>
          </thead>
          <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td>
                <%= link_to admins_customer_path(customer) do %>
                  <%= customer.last_name %><%= customer.first_name %>
                <% end %>
              </td>
              <td><%= customer.email %></td>
              <td>
                <% if customer.is_active? %>
                  <span class="label label-primary">有効</span>
                <% else %>
                  <span class="label label-danger">退会</span>
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
        <div class="col-md-3 offset-md-3">
          <%= paginate @customers %>
        </div
      </div>
    </div>
  </div>
</div>

app/views/admins/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 my-5">
      <h1><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h1>
      <table>
        <tr><th>会員ID</th><td><%= @customer.id %></td></tr>
        <tr><th>氏名</th><td><%= @customer.last_name %>　<%= @customer.first_name %></td></tr>
        <tr><th>フリガナ</th><td><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></td></tr>
        <tr><th>郵便番号</th><td><%= @customer.postal_code %></td></tr>
        <tr><th>住所</th><td><%= @customer.address %></td></tr>
        <tr><th>電話番号</th><td><%= @customer.telephone_number %></td></tr>
        <tr><th>メールアドレス</th><td><%= @customer.email %></td></tr>
      </table>
      <div class="d-flex flex-row bd-highlight mb-3">
        <div class="offset-md-1 mt-3">
          <%= link_to "編集する", edit_admins_customer_path(@customer), class: "btn btn-success" %>
        </div>
        <div class="offset-md-1 mt-3">
          <%= link_to "注文履歴一覧を見る", admin_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>