config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
  sessions: 'admins/sessions',
  passwords: 'admins/passwords',
  registrations: 'admins/registrations'
}
  devise_for :customers, controllers: {
  sessions: 'customers/sessions',
  passwords: 'customers/passwords',
  registrations: 'customers/registrations'
}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope module: :admins do
    get '/admin', to: 'homes#top'
  end

  namespace :admins do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]

  end

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update] do
      get :check
      patch :destroy
    end
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete :destroy_all
      end
    end
    resources :orders, only: [:index, :new, :create, :show]do
      collection do
        get :check
        get :thanks
      end
    end

  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.add_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def active_for_authentication?
    super && (self.is_active == true)
  end

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy

  attachment :image

  def add_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.all.page(params[:page])
  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.all
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admins_item_path(@item)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admins_item_path(@item)
  end


  private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price)
  end

end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :postage, :total_payment, :payment_method, :created_at, :updated_at)
  end

end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when Customer
      items_path
    end
  end


  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admins/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10s offset-md-1 my-5">
      <h1>商品編集</h1>
      <%= form_with model: @item,url: admins_item_path, method: :patch, local:true do |f| %>
        <div class="col-xs-4">
          <div class="form-group block-content">
            <div>
              <%= f.label :商品画像 %>
              <%= f.attachment_field :image %>
            </div>
          </div>
        </div>
        <div>
          <%= f.label :商品名, class: "col-sm-3 control-label" %>
          <%= f.text_field :name %>
        </div>
        <div>
          <%= f.label :商品説明, class: "col-sm-3 control-label" %>
          <%= f.text_area :introduction %>
        </div>
        <div>
          <%= f.label :税抜価格, class: "col-sm-3 control-label" %>
          <%= f.text_field :price %>円
        </div>
        <div class="offset-md-3 mt-3">
          <%= f.submit '変更を保存', class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 my-5">
      <div class="d-flex flex-row bd-highlight" >
        <h1>商品一覧</h1>
        <div class="col-md-2 offset-md-3">
          <%= link_to new_admins_item_path do %>
          <i class="fas fa-plus-circle fa-3x"></i>
          <% end %>
        </div>
      </div>
      <table class="table genre-index table-bordered">
        <thead>
          <tr>
            <td>商品ID</td>
            <td>商品名</td>
            <td>税抜価格</td>
          </tr>
        </thead>
        <tbody>
        <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td>
              <%= link_to admins_item_path(item) do %>
                <%= item.name %>
              <% end %>
            </td>
            <td><%= item.price %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <div class="col-md-3 offset-md-3">
        <%= paginate @items %>
      </div>
    </div>
  </div>
</div>

app/views/admins/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2 my-5">
      <h1>商品新規登録</h1>
      <%= form_with model: @item,url: admins_items_path, local:true do |f| %>
        <div class="col-xs-4">
          <div class="form-group block-content">
            <%= f.label :商品画像, class: "col-sm-3 control-label"  %>
            <%= f.attachment_field :image %>
          </div>
        </div>
        <div class="col-xs-6">
          <div class="form-group">
            <%= f.label :商品名, class: "col-sm-3 control-label"  %>
            <%= f.text_field :name %>
          </div>
          <div class="form-group">
            <%= f.label :商品説明, class: "col-sm-3 control-label"  %>
            <%= f.text_area :introduction %>
          </div>
          <div class="form-group">
            <%= f.label :税抜価格, class: "col-sm-3 control-label"  %>
            <%= f.text_field :price %>円
          </div>
        </div>
        <div class="col-md-6 offset-md-3">
          <%= f.submit '新規登録', class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10s offset-md-1 my-5">
      <h1>商品詳細</h1>
      <div class="d-flex flex-row bd-highlight">
        <div>
          <%= attachment_image_tag @item, :image, :fill, 200, 200, format: 'jpg', fallback: "cake.png" %>
        </div>
        <div　 class="d-flex flex-column bd-highlight ml-5">
          <table>
            <tbody>
              <tr>
                <td>商品名</td>
                <td><%= @item.name %></td>
              </tr>
              <tr>
                <td>商品説明</td>
                <td><%= @item.introduction %></td>
              </tr>
              <tr>
                <td>税込価格<br>(税抜価格)</td>
                <td><%= @item.add_tax_price.to_s(:delimited) %>(<%= @item.price.to_s(:delimited) %>)円</td>
              </tr>
            </tbody>
          </table>
          <div class="offset-md-3 mt-3">
            <%= link_to "編集する", edit_admins_item_path(@item), class: "btn btn-success" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 my-5">
      <h1>注文履歴詳細</h1>
      <table>
        <tr>
          <th>購入者</th>
          <td>
            <%= link_to admins_customer_path(@order.customer_id) do %>
              <%= @order.customer.last_name + @order.customer.first_name %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>〒<%= @order.postal_code %><%= @order.address %><br><%= @order.name %></td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
      </table>
      <div class="d-flex flex-row bd-highlight mt-3">
        <div>
          <table class="table table-bordered">
            <tr>
              <th>商品名</th>
              <th>単価(税込)</th>
              <th>数量</th>
              <th>小計</th>
            </tr>
              <% @order.order_items.each do |t| %>
                <tr>
                  <td><%= t.item.name %></td>
                  <td><%= t.item.add_tax_price %></td>
                  <td><%= t.amount %></td>
                  <td><%= (t.item.add_tax_price * t.amount) %></td>
                </tr>
              <% end %>
          </table>
        </div>
        <div class="d-flex align-items-end ml-5">
          <table>
            <tr>
              <th>商品合計</th>
              <td><%= (@order.total_payment - @order.postage) %>円</td>
            </tr>
            <tr>
              <th>送料</th>
              <td><%= @order.postage %>円</td>
            </tr>
            <tr>
              <th>請求合計金額</th>
              <td><%= @order.total_payment %>円</td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>