config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
  sessions: 'admins/sessions',
  passwords: 'admins/passwords',
  registrations: 'admins/registrations'
}
  devise_for :customers, controllers: {
  sessions: 'customers/sessions',
  passwords: 'customers/passwords',
  registrations: 'customers/registrations'
}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope module: :admins do
    get '/admin', to: 'homes#top'
  end

  namespace :admins do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]

  end

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update] do
      get :check
      patch :destroy
    end
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete :destroy_all
      end
    end
    resources :orders, only: [:index, :new, :create, :show]do
      collection do
        get :check
        get :thanks
      end
    end

  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.add_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def active_for_authentication?
    super && (self.is_active == true)
  end

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy

  attachment :image

  def add_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when Customer
      items_path
    end
  end


  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/6dda0aaec3.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand border-bottom ">
        <%= link_to image_tag("cake.png", :size =>'100x100'), '/' %>
        <ul class="navbar-nav ml-auto">
          <div class="d-flex flex-column bd-highlight mb-3">
            <div>
              <% if admin_signed_in? %>
              <div class="d-flex flex-row-reverse bd-highlight">
                <li class="nav-item">
                  <%= link_to "商品一覧", admins_items_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "会員一覧", admins_customers_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "注文履歴一覧", admin_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
                </li>

              </div>
              <% elsif customer_signed_in? %>
              <div class="d-flex flex-row-reverse bd-highlight">
                <li class="nav-item">
                  <%= link_to "マイページ", customer_path(current_customer.id), class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "商品一覧", items_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "カート", cart_items_path, class: "nav-link" %>
                  </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link" %>
                </li>
              </div>
              <% else %>
              <div class="d-flex flex-row-reverse bd-highlight">
                <li class="nav-item">
                  <%= link_to "About", about_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "商品一覧", items_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "新規登録", new_customer_registration_path, class: "nav-link" %>
                  </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_customer_session_path, class: "nav-link" %>
                </li>
              </div>
              <% end %>

            </div>

        <div>
          <%= text_field_tag :search %>
          <%= submit_tag 'Search' %>

        </div>
        </div>
        </ul>
      </nav>
    </header>
    <%= yield %>
    <footer>
      <div class="w-100 border-top" style="height: 100px;"></div>
    </footer>
  </body>
</html>